# Generated by Django 3.1.5 on 2021-01-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
